[project]
name = "appsCLI"
version = "0.1.0"
description = "Raycast for terminal"
readme = "README.md"


[project.scripts]
 apps = "appsCLI.entry:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/appsCLI"]
